import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    marginBottom: 12,
  },
  body: {
    flexDirection: 'row',
    width: '100%',
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#ffffff',
    minHeight: 55,
    alignItems: 'center',
    borderRadius: 12,
  },
  inputRightBorder: {
    borderRadius: 12,
  },
  containerRegion: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: '#F6F7FA',
    borderRightWidth: 4,
    height: '100%',
    width: 70,
  },
  regionTitle: {
    fontSize: 15,
    lineHeight: 20,
    marginRight: 12,
    color: '#1E1E20',
  },
  inputWrap: {
    flex: 1,
    position: 'relative',
    height: 55,
    justifyContent: 'center',
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
  },
  input: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 0,
    marginLeft: 0,
    alignSelf: 'stretch',
    position: 'relative',
    backgroundColor: 'transparent',
    color: '#1E1E20',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20,
  },
  resetIconWrap: {
    position: 'absolute',
    right: 0,
  },
  errorTextWrap: {
    marginTop: 5,
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  errorText: {
    color: '#FF450B',
    fontFamily: 'Raleway_400Regular',
    fontSize: 13,
    lineHeight: 18,
    alignSelf: 'flex-start',
    marginLeft: 12,
    marginBottom: 8,
    zIndex: -1,
  },
  fieldName: {
    position: 'absolute',
    top: 12,
    color: '#60626D',
    left: 12,
    fontFamily: 'Raleway_500Medium',
  },
});
